#Add effect id to remove it. to replace add following "effect_id=effect_id"
effects = ["farmersdelight:nourishment", "minecraft:hunger"]
#Add food item id to remove effects from it.
foods = []
#Prints all effects id into file
print_effect_id = false

