
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.iceandfire]
			dread_stone = true

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.iceandfire]
			dreadwood = true

	[types.leaves_type]

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.quark]
			pillar = true
			polished_vertical_slab = true
			vertical_slab = true

		[entries.stone_type.waystones]
			waystone = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.another_furniture]
			table = true
			flower_box = true
			shelf = true
			drawer = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

