[general]
giveJournal = false
holdToCast = true
showUnread = true
showToasts = true
defaultLineColor = false
rodDurabilityMultiplier = 1.0
crateWeight = 6
crateQuality = 1
[minigame]
doMinigame = true
doFeedback = true
doSuccessSound = true
doFailSound = true
minigameDifficulty = 1.6
[worldgen]
disableFishingBoat = true
disableEndOases = false
